//install node✅
//install express✅
//install dotenv✅
//express initialization✅
//express to make server✅
//express to make requests✅
//sending different response formats✅

//ejs and its usage✅
//display data in ejs✅


//post requests✅
//deleting items in an array✅
//editing items in an array✅


//cluster->database->collections->documents✅

//connecting to the Database✅
//saving in to the database✅
//getting information from the database✅
//editing info from the database✅
//deleting info in the db✅



//modularization✅

//cloudinary
//nodemailer
//auth and authorization